.PHONY: all jobs

all: jobs

jobs:
	@echo "Subdir make running with MAKEFLAGS = '$(MAKEFLAGS)'"
	@sleep 1 && echo "Task A done"
	@sleep 1 && echo "Task B done"
	@sleep 1 && echo "Task C done"
	@sleep 1 && echo "Task D done"

